In [2]:
import tensorflow as tf



tf.__version__

#determining the price of a house

#4-bedrooms, 2-bathrooms, 2-cargarage
""" Run length encoding
[0,0,0,1]
[0,1,0,0]
[0,1,0,0]
""" 

"""The shape of the input is shape=[3] and the shape of the output=[1] """

model = tf.keras.Sequential([
                             tf.keras.Input(shape=(3,)),#input layer
                             tf.keras.layers.Dense(100, activation="relu"),
                             tf.keras.layers.Dense(100, activation="relu"),
                             tf.keras.layers.Dense(100, activation="relu"),
                             tf.keras.layers.Dense(1, activation=None)
])


model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizer.Adam(lr=0.0001),
              metrics=["mae"])


model.fit(xTrain, yTrain, epochs=100)

'2.7.0'

In [24]:
import numpy as np

import matplotlib.pyplot as plt

x = np.array([-7.0, -4.0, -1.0, 2.0, 5.0, 8.0])

y = np.array([3.0, 6.0, 9.0, 12.0, 15.0, 18.0])


# plt.scatter(x,y)


xT = tf.constant(x, dtype=tf.float32)

xY = tf.constant(y, dtype=tf.float32)

xT = tf.expand_dims(xT, axis=1)
xY = tf.expand_dims(xY, axis=1)

xY,xT


(<tf.Tensor: shape=(6, 1), dtype=float32, numpy=
 array([[ 3.],
        [ 6.],
        [ 9.],
        [12.],
        [15.],
        [18.]], dtype=float32)>,
 <tf.Tensor: shape=(6, 1), dtype=float32, numpy=
 array([[-7.],
        [-4.],
        [-1.],
        [ 2.],
        [ 5.],
        [ 8.]], dtype=float32)>)

In [26]:
#creating the model
#compiling a model -> evaluating the performance of our model
#fitting a model

X = xT[0]

Y = xY[0]

tf.random.set_seed(42)


mode = tf.keras.Sequential([

                     tf.keras.layers.Dense(1) #-> we jsut need to output 1

])


#mean absolute error -> states the average times the model got the right answer
mode.compile(loss = tf.keras.losses.mae,
             optimizer = tf.keras.optimizers.SGD(),
             metrics=["mae"])


mode.fit(xT, xY, epochs=100)

#mode.fit(x_input, y_output, epochs=100)

Epoch 1/100
1/1 [==============================] - 1s 599ms/step - loss: 10.2150 - mae: 10.2150
Epoch 2/100
1/1 [==============================] - 0s 13ms/step - loss: 10.2025 - mae: 10.2025
Epoch 3/100
1/1 [==============================] - 0s 11ms/step - loss: 10.1900 - mae: 10.1900
Epoch 4/100
1/1 [==============================] - 0s 13ms/step - loss: 10.1775 - mae: 10.1775
Epoch 5/100
1/1 [==============================] - 0s 13ms/step - loss: 10.1650 - mae: 10.1650
Epoch 6/100
1/1 [==============================] - 0s 11ms/step - loss: 10.1525 - mae: 10.1525
Epoch 7/100
1/1 [==============================] - 0s 12ms/step - loss: 10.1400 - mae: 10.1400
Epoch 8/100
1/1 [==============================] - 0s 10ms/step - loss: 10.1275 - mae: 10.1275
Epoch 9/100
1/1 [==============================] - 0s 16ms/step - loss: 10.1150 - mae: 10.1150
Epoch 10/100
1/1 [==============================] - 0s 6ms/step - loss: 10.1025 - mae: 10.1025
Epoch 11/100
1/1 [==============================]

In [27]:
mode.predict([17.0])

array([[19.19101]], dtype=float32)