#hello world2

#Table of Contents
#Intro to tensors
#Information from tensors
#Manipulation of tensors
#Tensors & NumPy
#Using @tf.function -> speeding up regular python functions
#Using GPUs wiht TensorFlow 
#Exercices


"sdfdsfsdfds"


In [1]:
import tensorflow as tf
import numpy as np
#for version for tensorflow tf.__version__
tf.__version__


#===================


#SCALAR = no dimension
#tf.constant || numpy.array()
scalar = tf.constant(7)

hello = np.array(7)

scalar2 = tf.constant(hello)

scalar2 


vector = tf.constant([10,10])




#ndim = number of dimensions


vector.ndim

scalar.shape

TensorShape([])

In [2]:
matrix1 = tf.constant([[1,2],
                       [2,3],
                       [3,2]])

matrix1.shape

TensorShape([3, 2])

In [3]:
matrix2 = tf.constant([[10., 4.], 
                       [1., 2.],
                       [4., 8.]], dtype=tf.float16)

matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  4.],
       [ 1.,  2.],
       [ 4.,  8.]], dtype=float16)>

In [4]:
#increasing the number of dimensions

# dim = 3
# shape = 2x3x3

#*scalar has 0 dimensions
#*vector has 1 dimensions
#*matrix has 2 dimensions
#*tensor has n dimensions

In [5]:

tensor = tf.constant([[[1,2,2],
                     [2,2,2],
                     [3,3,3]], 
                    [[1,2,2],
                     [2,2,2],
                     [3,3,3]]])

tensor.shape

TensorShape([2, 3, 3])

In [6]:
#to change variable for tensors = myTensor.assign(newData)

scalarV = tf.Variable(2)

scalarC = tf.constant(2)


scalarV.assign(9)

scalarV, scalarC

(<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=9>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [7]:
#Creating random tensors

#not really random since you are spedifying the seed
#uniform = no negative numbers
#normal = negative and positive numbers
rndm = tf.random.Generator.from_seed(10)
rndm1 = rndm.normal(shape=(2,2))

rndm0 = tf.random.Generator.from_seed(10)
rndm2 = rndm0.normal(shape=(2,2))


rdm3 = tf.random.normal(shape=(2,2))
rndm1, rndm2, rdm3

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.29604465, -0.21134205],
        [ 0.01063002,  1.5165398 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.29604465, -0.21134205],
        [ 0.01063002,  1.5165398 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 1.0621036 ,  2.5661457 ],
        [-0.5003115 , -0.76677424]], dtype=float32)>)

In [8]:
#Shuffling the elements inside the tensor
#Shuffle does not shuffle one dimensionals 
#tf.random.set_seed(12) -> not change the random state even after refresh

tf.random.set_seed(12)

ourTensor = tf.constant([[1,10, 11],
                         [4, 99, 52],
                         [34, 87, 56]])


ourTensor2 = tf.constant([[1,10, 11],
                          [4, 99, 52],
                          [34, 87, 56]])
#if you set it to the same seed the they will be the same no matter what
#if the globl and operational are not the same then they will not be the same but will not change after refresh
tf.random.shuffle(ourTensor, seed=12), tf.random.shuffle(ourTensor2, seed=12)


(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[34, 87, 56],
        [ 4, 99, 52],
        [ 1, 10, 11]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[34, 87, 56],
        [ 1, 10, 11],
        [ 4, 99, 52]], dtype=int32)>)

In [9]:
#random shuffling 1s array

d = tf.constant([1,2,3])


tf.random.shuffle(d)

#changing the data type of the tensor 
s = tf.Variable([[1,2,3],
                 [4,5,6],
                 [7,8,9]], dtype=tf.int16)
s




<tf.Variable 'Variable:0' shape=(3, 3) dtype=int16, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int16)>

Numpy arrays and shaping

In [10]:
#We shuffle it so that the model will not be biased
#numpy arrays vs tensorflow tensor = tensors are faster to be run on a GPU



#creating tensors with 0's asn 1's
tf.ones([2,2])

tf.zeros([])


import numpy as np

#capital for a matrix or a tensor and non-capital for a vector

npA = np.arange(1, 10,dtype=np.int32)

npA



newTensor = tf.constant(npA, shape=(3,3))
newTensor
# tf.reshape(newTensor, [3,3])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [11]:
#Rank4 tensor


# r4 = tf.random.uniform(shape=(4,3,3,2))


r4 = np.arange(1, 65, dtype=np.int32)

rank4 = tf.constant(r4,shape=(4, 4, 2, 2))
rank4.ndim


ra4 = tf.zeros([4,4,4,4])

ra4.ndim

4

In [12]:
r4 = tf.zeros(shape=[2,4,2,2])

r4[0]



# print(f"""
#       Dtype of every element: {r4.dtype}
#       Number of dimenstion || rank: {r4.ndim}
#       Shape of the tensor: {r4.shape}
#       Elements along the 0 axis: {r4.shape[0]}
#       Elements along the last axis: {r4.shape[-1]}
#       Total number of elements: {tf.size(r4)}""")




#print(r4)

ourT = tf.constant([[1,3,3],
                    [4,5,6],
                    [7,8,9]])


ourF = tf.random.uniform(shape=(2,3,4))
#print(ourF)


#to get the idx of the tensors, just like an array but only one [] brackets



ourF[:2,:1, :2 ]



#create a rank 2 tensor 

r2 = tf.constant([[1,2], 
                  [9,11]])

r2.ndim

r2[-1, -1]


#adding in extra diemension

#adding new axis or dimension = tf.newaxis
r3 = r2[..., tf.newaxis]


r3



tf.expand_dims(r2, axis =-1) # expand the final axis adding dimension at the end






<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 1],
        [ 2]],

       [[ 9],
        [11]]], dtype=int32)>

In [13]:
tf.expand_dims(r2, axis = 1) #adds in another dimension at the middle 
tf.expand_dims(r2, axis=0) #adds in another dimesions at the front

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 9, 11]]], dtype=int32)>

In [14]:
#adding values to a tensor using the addition operator


ten = tf.constant( [[10,7], [0, 1]])


#this will add 10 within our elements inside the tensor
ten + 10

ten * 10

ten - 7


tf.add(ten, 10)
tf.multiply(ten, 2)

tf.subtract(ten, 7)

tf.divide(ten, 2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [0. , 0.5]])>

In [15]:
#Matrix multiplication

tf.matmul(ten, ten)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  77],
       [  0,   1]], dtype=int32)>

In [16]:
o = tf.constant([[1,2,5],
                 [7,2,1],
                 [3,3,3]])

o2 = tf.constant([[3,5,5],
                  [6,7,11]])

o2 = tf.reshape(o2,[3,2])
tf.matmul(o, o2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[48, 72],
       [38, 58],
       [45, 66]], dtype=int32)>

In [17]:
oa = tf.constant([[1,2,1],
                 [3,4,1]])

oh = tf.constant([[3,5],
                  [6,7],
                  [1,8]])


tf.matmul(o, o2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[48, 72],
       [38, 58],
       [45, 66]], dtype=int32)>

In [18]:
#transpose will flip the axis
#/

tf.transpose(oh), tf.reshape(oh, [2,3])

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 6, 1],
        [5, 7, 8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 5, 6],
        [7, 1, 8]], dtype=int32)>)

In [19]:
tf.tensordot(oa, oh, axes=1)
tf.transpose(oa)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4],
       [1, 1]], dtype=int32)>

In [20]:
#Changing the data type of a tensor

B = tf.constant([1,2,3])

A = tf.constant([1.1,2.2,3.3])

A.dtype


A = tf.cast(A, dtype=tf.float16)
A

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1.1, 2.2, 3.3], dtype=float16)>

In [21]:
#aggregating tensors = grouping and making them into smaller amout of values

C = tf.constant(np.random.randint(0, 100, size=50))

C = tf.cast(C, dtype=tf.float32)

#getting the maximun, minimum, mean, and sum
print(tf.reduce_min(C))
print(tf.reduce_mean(C)) 
print(tf.reduce_max(C))
print(tf.reduce_sum(C))
print(tf.size(C))
print(C)



#gettting the variance of the tensor
import tensorflow_probability as tfp

print(tfp.stats.variance(C))

#For the stadard devaition, the tensor needs to be a float since it is stats
print(tfp.stats.stddev(C))




tf.Tensor(7.0, shape=(), dtype=float32)
tf.Tensor(47.16, shape=(), dtype=float32)
tf.Tensor(99.0, shape=(), dtype=float32)
tf.Tensor(2358.0, shape=(), dtype=float32)
tf.Tensor(50, shape=(), dtype=int32)
tf.Tensor(
[52. 79. 25. 64. 84. 62. 48. 63. 17. 11. 59. 42.  7. 92. 10. 97. 32. 71.
 75. 22. 87. 40. 17. 65. 49. 24. 39. 18. 89. 64. 76. 43. 99. 44.  9. 20.
 22. 23. 14. 51. 15. 51. 83. 61. 60. 12.  7. 75. 80.  9.], shape=(50,), dtype=float32)
tf.Tensor(779.93445, shape=(), dtype=float32)
tf.Tensor(27.927307, shape=(), dtype=float32)


In [28]:
tf.math.reduce_variance(C)


tf.math.reduce_std(C)

<tf.Tensor: shape=(), dtype=float32, numpy=27.927307>

In [41]:
#Fiding the maximum and minimun positional value



tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
tf.argmax(F) #-> gets the idx of it



print(F[tf.argmax(F)])


print(tf.reduce_max(F))



print(tf.argmin(F))

print(F[tf.argmin(F)])
F


tf.Tensor(0.9671384, shape=(), dtype=float32)
tf.Tensor(0.9671384, shape=(), dtype=float32)
tf.Tensor(16, shape=(), dtype=int64)
tf.Tensor(0.009463668, shape=(), dtype=float32)


<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [52]:
G = tf.random.uniform(shape=(2,10))


print(tf.argmin(G[0]))

G

tf.Tensor(7, shape=(), dtype=int64)


<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[0.9198024 , 0.9021473 , 0.41526616, 0.08292842, 0.10040832,
        0.06153822, 0.7671492 , 0.05545342, 0.13344252, 0.874243  ],
       [0.12639618, 0.07750273, 0.8898996 , 0.8573204 , 0.40581453,
        0.05270422, 0.8703762 , 0.39350355, 0.41915298, 0.32164288]],
      dtype=float32)>

In [62]:
H = tf.constant(tf.random.uniform(shape=[100]), shape= (1,1,1,1,100))


H

<tf.Tensor: shape=(1, 1, 1, 1, 100), dtype=float32, numpy=
array([[[[[0.5852475 , 0.9927181 , 0.3110503 , 0.44591808, 0.8970233 ,
           0.6452199 , 0.04707861, 0.43374014, 0.6919069 , 0.2356894 ,
           0.54439366, 0.45189762, 0.8827189 , 0.5912421 , 0.5673742 ,
           0.39240313, 0.1258322 , 0.94337356, 0.19854975, 0.45738494,
           0.5995703 , 0.2941928 , 0.7386502 , 0.05998945, 0.12787127,
           0.6411879 , 0.4465276 , 0.22277546, 0.12308025, 0.7215545 ,
           0.2790836 , 0.27117848, 0.32610834, 0.60007644, 0.84208965,
           0.65200114, 0.8364419 , 0.5823555 , 0.7090963 , 0.23557973,
           0.17463195, 0.04684031, 0.03135979, 0.9831356 , 0.9527756 ,
           0.1761508 , 0.98687565, 0.03847897, 0.5953833 , 0.8765999 ,
           0.9711665 , 0.326411  , 0.04698968, 0.4017011 , 0.39505637,
           0.7639568 , 0.68583596, 0.33126056, 0.33389914, 0.85423064,
           0.29443562, 0.27368915, 0.91453254, 0.39472067, 0.1648544 ,
           0.64951

In [63]:

#This will remove one dimensionals in the tensor 
G_squeezed = tf.squeeze(H) 

G_squeezed

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([0.5852475 , 0.9927181 , 0.3110503 , 0.44591808, 0.8970233 ,
       0.6452199 , 0.04707861, 0.43374014, 0.6919069 , 0.2356894 ,
       0.54439366, 0.45189762, 0.8827189 , 0.5912421 , 0.5673742 ,
       0.39240313, 0.1258322 , 0.94337356, 0.19854975, 0.45738494,
       0.5995703 , 0.2941928 , 0.7386502 , 0.05998945, 0.12787127,
       0.6411879 , 0.4465276 , 0.22277546, 0.12308025, 0.7215545 ,
       0.2790836 , 0.27117848, 0.32610834, 0.60007644, 0.84208965,
       0.65200114, 0.8364419 , 0.5823555 , 0.7090963 , 0.23557973,
       0.17463195, 0.04684031, 0.03135979, 0.9831356 , 0.9527756 ,
       0.1761508 , 0.98687565, 0.03847897, 0.5953833 , 0.8765999 ,
       0.9711665 , 0.326411  , 0.04698968, 0.4017011 , 0.39505637,
       0.7639568 , 0.68583596, 0.33126056, 0.33389914, 0.85423064,
       0.29443562, 0.27368915, 0.91453254, 0.39472067, 0.1648544 ,
       0.64951265, 0.5388243 , 0.245669  , 0.9451741 , 0.35888386,
       0.30763

In [74]:
helloAr = [1,2,3,4] 


l = ['hello', 'world']
#one_hot


tf.one_hot(helloAr, depth=len(helloAr))



<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [84]:
#creating another tensor with 'tf.range'


I = tf.range(1,10)

tf.square(I) #squaring


tf.sqrt(tf.cast(I, dtype=tf.float16)) #square root for our tensor

tf.math.log(tf.cast(I, dtype=tf.float16)) #logs requeire math funcion



<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

In [90]:
K = tf.range(1,10)

tf.reshape(K, shape=(3,3))



<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [111]:
#numpys



L = tf.constant(np.array([2,3,4,5]))


print(L)
# you can conver numpy arrays tp24
np.array(L), L.numpy()


ourA = np.arange(1,25, dtype=np.int32)


M = tf.constant(np.array([1,2,3,4,5]))

#M is a tensor now


np.array(M), M.numpy()


O = tf.constant([[1,2],
                 [3,4]])

O.numpy()


myn = np.arange(1,25,dtype=np.int32)

myn[:5]
# O

tf.Tensor([2 3 4 5], shape=(4,), dtype=int64)


array([1, 2, 3, 4, 5], dtype=int32)