#hello world2

#Table of Contents
#Intro to tensors
#Information from tensors
#Manipulation of tensors
#Tensors & NumPy
#Using @tf.function -> speeding up regular python functions
#Using GPUs wiht TensorFlow 
#Exercices


"sdfdsfsdfds"


In [1]:
import tensorflow as tf
import numpy as np
#for version for tensorflow tf.__version__
tf.__version__


#===================


#SCALAR = no dimension
#tf.constant || numpy.array()
scalar = tf.constant(7)

hello = np.array(7)

scalar2 = tf.constant(hello)

scalar2 


vector = tf.constant([10,10])




#ndim = number of dimensions


vector.ndim


scalar.shape

TensorShape([])

In [2]:
matrix1 = tf.constant([[1,2],
                       [2,3],
                       [3,2]])

matrix1.shape

TensorShape([3, 2])

In [3]:
matrix2 = tf.constant([[10., 4.], 
                       [1., 2.],
                       [4., 8.]], dtype=tf.float16)

matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  4.],
       [ 1.,  2.],
       [ 4.,  8.]], dtype=float16)>

In [4]:
#increasing the number of dimensions

# dim = 3
# shape = 2x3x3

#*scalar has 0 dimensions
#*vector has 1 dimensions
#*matrix has 2 dimensions
#*tensor has n dimensions

In [5]:

tensor = tf.constant([[[1,2,2],
                     [2,2,2],
                     [3,3,3]], 
                    [[1,2,2],
                     [2,2,2],
                     [3,3,3]]])

tensor.shape

TensorShape([2, 3, 3])

In [6]:
#to change variable for tensors = myTensor.assign(newData)

scalarV = tf.Variable(2)

scalarC = tf.constant(2)


scalarV.assign(9)

scalarV, scalarC

(<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=9>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [310]:
#Creating random tensors

#not really random since you are spedifying the seed
#uniform = no negative numbers
#normal = negative and positive numbers
rndm = tf.random.Generator.from_seed(10)
rndm1 = rndm.normal(shape=(2,2))

rndm0 = tf.random.Generator.from_seed(10)
rndm2 = rndm0.normal(shape=(2,2))


rdm3 = tf.random.normal(shape=(2,2))
rndm1, rndm2, rdm3

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.29604465, -0.21134205],
        [ 0.01063002,  1.5165398 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.29604465, -0.21134205],
        [ 0.01063002,  1.5165398 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-1.1064562 ,  0.96851546],
        [ 1.6931907 ,  2.2043836 ]], dtype=float32)>)

In [279]:
#Shuffling the elements inside the tensor
#Shuffle does not shuffle one dimensionals 
#tf.random.set_seed(12) -> not change the random state even after refresh

tf.random.set_seed(12)

ourTensor = tf.constant([[1,10, 11],
                         [4, 99, 52],
                         [34, 87, 56]])


ourTensor2 = tf.constant([[1,10, 11],
                          [4, 99, 52],
                          [34, 87, 56]])
#if you set it to the same seed the they will be the same no matter what
#if the globl and operational are not the same then they will not be the same but will not change after refresh
tf.random.shuffle(ourTensor, seed=12), tf.random.shuffle(ourTensor2, seed=12)


(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[34, 87, 56],
        [ 4, 99, 52],
        [ 1, 10, 11]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[34, 87, 56],
        [ 1, 10, 11],
        [ 4, 99, 52]], dtype=int32)>)

In [220]:
#random shuffling 1s array

d = tf.constant([1,2,3])


tf.random.shuffle(d)

#changing the data type of the tensor 
s = tf.Variable([[1,2,3],
                 [4,5,6],
                 [7,8,9]], dtype=tf.int16)
s




<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

Numpy arrays and shaping

In [318]:
#We shuffle it so that the model will not be biased
#numpy arrays vs tensorflow tensor = tensors are faster to be run on a GPU




tf.ones([2,2])

tf.zeros([])


import numpy as np

#capital for a matrix or a tensor and non-capital for a vector

npA = np.arange(1, 10,dtype=np.int32)

npA



newTensor = tf.constant(npA, shape= (3,3))
newTensor
# tf.reshape(newTensor, [3,3])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>